modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="The_SlayerMC" #optional
authors="The_SlayerMC" #optional

[[mods]] #mandatory
modId="corruptedones" #mandatory
version="0.1.0" #mandatory
displayName="Curroupted Ones" #mandatory
description='''
Corrupted Entitys
'''

[[dependencies.corruptedones]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.corruptedones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"