package net.slayer.corrupted;

import java.util.ArrayList;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.slayer.corrupted.proxy.CommonProxy;
import net.slayer.corrupted.util.LangRegistry;
import net.slayer.corrupted.util.SlayerAPI;

@Mod(name = SlayerAPI.MOD_NAME, modid = SlayerAPI.MOD_ID, version = SlayerAPI.MOD_VERSION)
public class CorruptedOnes {

	@Instance(SlayerAPI.MOD_ID)
	public static CorruptedOnes instance;

	@SidedProxy(clientSide = "net.slayer.corrupted.proxy.ClientProxy", serverSide = "net.slayer.corrupted.proxy.CommonProxy")
	public static CommonProxy proxy;
	
	public static SimpleNetworkWrapper wrapper;
		
	@EventHandler
	public static void preInit(FMLPreInitializationEvent event) {
		proxy.preInit(event);
		proxy.registerClient();
		proxy.clientPreInit();
		ArrayList<String> author = new ArrayList<String>();
		author.add("The_SlayerMC");
		event.getModMetadata().autogenerated = false;
		event.getModMetadata().credits = SlayerAPI.Colour.AQUA + "The_SlayerMC - Owner/Creator ";
		event.getModMetadata().description = "Desc";
		event.getModMetadata().modId = SlayerAPI.MOD_ID;
		event.getModMetadata().url = "https://www.slayermods.net";
		event.getModMetadata().name = SlayerAPI.MOD_NAME;
		event.getModMetadata().version = SlayerAPI.MOD_VERSION;
		event.getModMetadata().logoFile = "assets/corruptedones/textures/logo.png";
		event.getModMetadata().authorList = author;
	}

	@EventHandler
	public static void init(FMLInitializationEvent event) {
		proxy.init(event);
		proxy.clientInit(event);
	}

	@EventHandler
	public static void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}

	@EventHandler
	public static void serverStarting(FMLServerStartingEvent event) {
		SlayerAPI.logger.info("Starting server...");
		proxy.serverStarting(event);
	}
}
